# Generated by Django 6.0.1 on 2026-02-01 13:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(db_index=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_equipment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_flowrate', models.FloatField(blank=True, null=True)),
                ('avg_pressure', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='api_dataset_uploade_babbef_idx'), models.Index(fields=['filename'], name='api_dataset_filenam_db7c67_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(db_index=True, max_length=255)),
                ('equipment_type', models.CharField(choices=[('Pump', 'Pump'), ('Compressor', 'Compressor'), ('Valve', 'Valve'), ('HeatExchanger', 'Heat Exchanger'), ('Reactor', 'Reactor'), ('Condenser', 'Condenser'), ('Tank', 'Tank'), ('Other', 'Other')], db_index=True, max_length=50)),
                ('flowrate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pressure', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature', models.FloatField()),
                ('is_pressure_outlier', models.BooleanField(db_index=True, default=False)),
                ('is_temperature_outlier', models.BooleanField(db_index=True, default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.dataset')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['equipment_name'],
                'indexes': [models.Index(fields=['dataset_id', 'equipment_type'], name='api_equipme_dataset_5f63bb_idx'), models.Index(fields=['equipment_name'], name='api_equipme_equipme_e29dda_idx'), models.Index(fields=['dataset_id', 'is_pressure_outlier', 'is_temperature_outlier'], name='api_equipme_dataset_a2956f_idx')],
            },
        ),
    ]
